
//MainMenu
export const ADD_TO_MAINMENU = 'ADD_TO_MAINMENU'


//Login
export const SET_AUTHENTICATION= 'SET_AUTHENTICATION'
export const SET_LOGIN_ERROR= 'SET_LOGIN_ERROR'

//Business App
export const SET_BUSINESSAPPS = 'SET_BUSINESSAPPS'
export const GET_BUSINESSAPPS = 'GET_BUSINESSAPPS'

export const SET_ONEBIZAPP_DETAIL = 'SET_ONEBIZAPP_DETAIL'
export const GET_ONEBIZAPP_DETAIL = 'GET_ONEBIZAPP_DETAIL'

export const STOP_ONEBIZAPP_SUCCESS = 'STOP_ONEBIZAPP_SUCCESS'
export const RESUME_ONEBIZAPP_SUCCESS = 'RESUME_ONEBIZAPP_SUCCESS'
//Vendor
export const SET_VENDORS= 'SET_VENDORS'
export const GET_VENDORS= 'GET_VENDORS'

export const SET_ONEVENDOR_DETAIL = 'SET_ONEVENDOR_DETAIL'
export const GET_ONEVENDOR_DETAIL = 'GET_ONEVENDOR_DETAIL'

export const STOP_ONEVENDOR_SUCCESS = 'STOP_ONEVENDOR_SUCCESS'
export const RESUME_ONEVENDOR_SUCCESS = 'RESUME_ONEVENDOR_SUCCESS'
export const SET_VENDORS_DROPDOWN_LIST= 'SET_VENDORS_DROPDOWN_LIST'
//Room
export const SET_ROOMS= 'SET_ROOMS'
export const GET_ROOMS= 'GET_ROOMS'

export const SET_ONEROOM_DETAIL = 'SET_ONEROOM_DETAIL'
export const GET_ONEROOM_DETAIL = 'GET_ONEROOM_DETAIL'

export const STOP_ONEROOM_SUCCESS = 'STOP_ONEROOM_SUCCESS'
export const RESUME_ONEROOM_SUCCESS = 'RESUME_ONEROOM_SUCCESS'
//Org
export const SET_BIZ_ORG_LIST = 'SET_BIZ_ORG_LIST'
//task
export const SET_TASK_WAITING = 'SET_TASK_WAITING'
export const SET_TASK_HISTORY = 'SET_TASK_HISTORY'
export const SET_TASK_HISTORY_QUERY = 'SET_TASK_HISTORY_QUERY'
export const SET_ONETASK_REQUIREMENT_CHANGE= 'SET_ONETASK_REQUIREMENT_CHANGE'
export const SET_ONETASK_DATA_CHANGE= 'SET_ONETASK_DATA_CHANGE'
export const SET_ONETASK_DATA_QUERY= 'SET_ONETASK_DATA_QUERY'
export const SET_ONETASK_PROGRAM_DEPLOY= 'SET_ONETASK_PROGRAM_DEPLOY'

export const ADD_ATTACHMENT='ADD_ATTACHMENT'
export const DEL_ATTACHMENT='DEL_ATTACHMENT'

//common combobox
export const SET_COMBOBOX_ITEMS='SET_COMBOBOX_ITEMS'
export const GET_COMBOBOX_ITEMS='GET_COMBOBOX_ITEMS'


//notice
export const SET_NOTICE_UNREAD='SET_NOTICE_UNREAD'
export const SET_NOTICE_RECEIVE='SET_NOTICE_RECEIVE'
export const SET_NOTICE_SEND='SET_NOTICE_SEND'
export const READ_NOTICE_SUCCESS='READ_NOTICE_SUCCESS'
export const DELETE_NOTICE_SUCCESS='DELETE_NOTICE_SUCCESS'

//zabbix
export const SET_ZIBEVENTS='SET_ZIBEVENTS'
export const SET_HEALTH='SET_HEALTH'
export const SET_COUNTING='SET_COUNTING'

export const SET_MONBIZ='SET_MONBIZ'
export const CREATE_MONBIZ_SUCCESS = 'CREATE_MONBIZ_SUCCESS'
export const DELETE_MONBIZ_SUCCESS = 'DELETE_MONBIZ_SUCCESS'

export const SET_MONSERVER='SET_SERVER'
export const CREATE_MONSERVER_SUCCESS = 'CREATE_MONSERVER_SUCCESS'
export const DELETE_MONSERVER_SUCCESS = 'DELETE_MONSERVER_SUCCESS'

export const SET_MONDB='SET_MONDB'
export const CREATE_MONDB_SUCCESS = 'CREATE_MONDB_SUCCESS'
export const DELETE_MONDB_SUCCESS = 'DELETE_MONDB_SUCCESS'

//ip management
export const SET_IPARRAY= ' SET_IPARRAY'
export const SET_IP_NETSELECTED= 'SET_IP_NETSELECTED'
export const SET_IPNETARRAY='SET_IPNETARRAY'
export const SET_IPNET='SET_IPNET'
export const DEL_IPNET='DEL_IPNET'
export const SET_EDITNET='SET_EDITNET'
export const SET_ALERTOBJ='SET_ALERTOBJ'

//project apply  management
export const SET_PROJECT_LIST= ' SET_PROJECT_LIST'
export const SET_ONE_PROJECT_DETAIL = ' SET_ONE_PROJECT_DETAIL'
export const SET_PROJECT_QUERY = ' SET_PROJECT_QUERY'
export const SET_PROJECTAPPLY_ADD_ENTERGUARD = ' SET_PROJECTAPPLY_ADD_ENTERGUARD'
export const DELETE_PROJECT_SUCCESS = ' DELETE_PROJECT_SUCCESS'

//project purchase  management
export const SET_PROJECT_PURCHASE_LIST= ' SET_PROJECT_PURCHASE_LIST'
export const SET_ONE_PROJECT_PROCUREMENT_DETAIL= ' SET_ONE_PROJECT_PROCUREMENT_DETAIL'
export const SET_PROCUREMENT_DETAIL_ENTERGUARD= ' SET_PROCUREMENT_DETAIL_ENTERGUARD'
export const DELETE_PROJECT_PROCUREMENT_SUCCESS= ' DELETE_PROJECT_PROCUREMENT_SUCCESS'

//contract register
export const SET_CONTRACT_QUERY = ' SET_CONTRACT_QUERY'
export const SET_CONTRACT_LIST = ' SET_CONTRACT_LIST'
export const SET_CONTRACT_REGISTER_DETAIL='SET_CONTRACT_REGISTER_DETAIL'
export const SET_CONTRACT_REGISTER_DETAIL_ENTERGUARD='SET_CONTRACT_REGISTER_DETAIL_ENTERGUARD'
export const DELETE_CONTRACT_REGISTER_DETAIL_PAYMENT='DELETE_CONTRACT_REGISTER_DETAIL_PAYMENT'
export const SET_CONTRACT_REGISTER_DETAIL_PAYDETAIL_ENTERGUARD='SET_CONTRACT_REGISTER_DETAIL_PAYDETAIL_ENTERGUARD'
export const ADD_CONTRACT_REGISTER_DETAIL_PAYMENT='ADD_CONTRACT_REGISTER_DETAIL_PAYMENT'
export const SET_CONTRACT_REGISTER_DETAIL_VENDORID='SET_CONTRACT_REGISTER_DETAIL_VENDORID'
export const SET_CONTRACT_REGISTER_DETAIL_PID='SET_CONTRACT_REGISTER_DETAIL_PID'
export const SET_CONTRACT_REGISTER_DETAIL_CONTRACTFILEID='SET_CONTRACT_REGISTER_DETAIL_CONTRACTFILEID'

//contract acceptance
export const SET_CONTRACT_ACCEPTANCE_DETAIL_ENTERGUARD = ' SET_CONTRACT_ACCEPTANCE_DETAIL_ENTERGUARD'

//contract exec plan
export const SET_CONTRACT_EXEC_PLAN_LIST='SET_CONTRACT_EXEC_PLAN_LIST'
export const SET_CONTRACT_DETAIL='SET_CONTRACT_DETAIL'
export const SET_CONTRACT_BUSINESS_LIST='SET_CONTRACT_BUSINESS_LIST'
export const SET_CONTRACT_DETAIL_READONLY='SET_CONTRACT_DETAIL_READONLY'
export const SET_CONTRACT_HWMAN_DEL='SET_CONTRACT_HWMAN_DEL'
export const SET_CONTRACT_HWWARRANTY_DEL='SET_CONTRACT_HWWARRANTY_DEL'

//inspection
export const SET_INSPECTION_TPL_LIST='SET_INSPECTION_TPL_LIST'
export const SET_INSPECTION_TPL_DETAIL='SET_INSPECTION_TPL_DETAIL'
export const SET_INSPECTION_TPL_DETAIL_STATE='SET_INSPECTION_TPL_DETAIL_STATE'
export const DEL_INSPECTION_TPL_ITEM='DEL_INSPECTION_TPL_ITEM'
export const SET_INSPECTION_PLAN_DETAIL='SET_INSPECTION_PLAN_DETAIL'
export const SET_INSPECTION_PLAN_DETAIL_STATE='SET_INSPECTION_PLAN_DETAIL_STATE'

