
CREATE TABLE `sys_group` (
  `GROUP_ID` int(16) NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `GROUP_CODE` varchar(32) DEFAULT NULL COMMENT '角色编码',
  `GROUP_NAME` varchar(100) DEFAULT NULL COMMENT '角色名称',
  `CUSER_ID` int(16) DEFAULT NULL COMMENT '创建人',
  `CDATE` datetime DEFAULT NULL COMMENT '创建时间',
  `EUSER_ID` int(16) DEFAULT NULL COMMENT '修改人',
  `EDATE` datetime DEFAULT NULL COMMENT '修改时间',
  `VALID_TYPE` varchar(1) DEFAULT NULL COMMENT '有效标志,1-有效,0-无效',
  PRIMARY KEY (`GROUP_ID`),
  UNIQUE KEY `PK_SYS_GROUP` (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `sys_privilege` (
  `PRIVILEGE_ID` int(16) NOT NULL AUTO_INCREMENT COMMENT '权限流水号',
  `MENU_NAME` varchar(100) DEFAULT NULL COMMENT '菜单名称',
  `MENU_TYPE` varchar(1) DEFAULT NULL COMMENT '菜单类型，0-菜单，1-按钮',
  `URL` varchar(100) DEFAULT NULL,
  `PARENTID` int(16) DEFAULT NULL COMMENT '父节点ID',
  `CUSER_ID` int(16) DEFAULT NULL COMMENT '创建者',
  `CDATE` datetime DEFAULT NULL COMMENT '创建时间',
  `EUSER_ID` int(16) DEFAULT NULL COMMENT '修改者',
  `EDATE` datetime DEFAULT NULL COMMENT '修改时间',
  `SORT` int(5) DEFAULT NULL COMMENT '序号',
  `IMAGE` varchar(100) DEFAULT NULL COMMENT '图片地址',
  PRIMARY KEY (`PRIVILEGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `sys_user` (
  `USER_ID` int(16) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `PASSWORD` varchar(100) NOT NULL COMMENT '密码',
  `PASS_MOD_DATE` datetime DEFAULT NULL COMMENT '密码修改日期',
  `VALID_TYPE` varchar(1) DEFAULT '0' COMMENT '有效标识，1-有效，0-无效',
  `USERNAME` varchar(100) DEFAULT NULL COMMENT '用户姓名',
  `USERCODE` varchar(32) DEFAULT NULL COMMENT '用户登录名',
  `ORG_ID` int(16) DEFAULT NULL COMMENT '组织机构ID',
  `USER_SORT` int(5) DEFAULT NULL COMMENT '内部顺序',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `PK_SYS_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `sys_group_privilege` (
  `ID` int(16) NOT NULL AUTO_INCREMENT,
  `GROUP_ID` int(16) DEFAULT NULL COMMENT '角色ID',
  `PRIVILEGE_ID` int(16) DEFAULT NULL COMMENT '权限ID',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PK_SYS_GROUP_PRIVILEGE` (`ID`),
  KEY `FK_GROUP_PRIVILEGE_GROUPID` (`GROUP_ID`),
  KEY `FK_GROUP_PRIVILEGE_PRIVILEGEID` (`PRIVILEGE_ID`),
  CONSTRAINT `FK_GROUP_PRIVILEGE_GROUPID` FOREIGN KEY (`GROUP_ID`) REFERENCES `sys_group` (`GROUP_ID`),
  CONSTRAINT `FK_GROUP_PRIVILEGE_PRIVILEGEID` FOREIGN KEY (`PRIVILEGE_ID`) REFERENCES `sys_privilege` (`PRIVILEGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `sys_user_group` (
  `ID` int(16) NOT NULL AUTO_INCREMENT COMMENT '用户角色流水号',
  `USER_ID` int(16) DEFAULT NULL COMMENT '用户ID',
  `GROUP_ID` int(16) DEFAULT NULL COMMENT '角色ID',
  PRIMARY KEY (`ID`),
  KEY `PK_SYS_USER_GROUP` (`ID`),
  KEY `FK_USER_GROUP_USERID` (`USER_ID`),
  KEY `FK_USER_GROUP_GROUPID` (`GROUP_ID`),
  CONSTRAINT `FK_USER_GROUP_GROUPID` FOREIGN KEY (`GROUP_ID`) REFERENCES `sys_group` (`GROUP_ID`),
  CONSTRAINT `FK_USER_GROUP_USERID` FOREIGN KEY (`USER_ID`) REFERENCES `sys_user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;